[package]
name = "lox-rs"
version = "0.1.0"
authors = ["Hugo Saracino <hugo.saracino@gmail.com>"]
edition = "2018"

[lib]
name = "lox"
path = "src/lib.rs"

[[bin]]
name = "lox"
path = "src/bin/lox.rs"

[dependencies]
itertools = "0.9.0"
rustyline = "6.1.2"
structopt = "0.3.14"